api = "0.4"

[buildpack]
  id = "paketo-community/python"
  name = "Paketo Python Buildpack"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.171"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.0.119"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.140"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.171"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.140"

[[order]]

  [[order.group]]
    id = "paketo-community/conda"
    version = "0.0.113"

[[order]]

  [[order.group]]
    id = "paketo-community/cpython"
    version =  "0.1.0"

  [[order.group]]
    id = "paketo-community/python-start"
    version = "0.1.0"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "4.0.0"
    optional = true
